### ISSUE TITLE
在手机上面测试一直返回-1.0

### ISSUE THREAD

**Issue by hutuxiansheng** [fengFly2014/Android_Face_Verification-#1]
02-15 08:35:33.330 32632 32632 E log     : initialize start
02-15 08:35:44.724 32632 32632 E log     : initialize done
02-15 08:35:45.182 32632 32632 E result  : similiarity = -1.0

**Comment by fengFly2014** [comment]
这个这个很有可能是两张图片的路径设置的有问题，找两张质量不错的图片试一下，如果还返回-1，一般是路径的问题。
